version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - './api:/api'
    ports:
     - "5000:5000"
    depends_on:
      - redis
        
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - './celery-queue:/queue'
    depends_on:
      - redis

  redis:
    image: redis
